services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: always
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui: